# Generated by Django 2.0.5 on 2018-06-13 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedToSyndicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Invited To Syndicate',
            },
        ),
        migrations.CreateModel(
            name='Syndicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('focus', models.CharField(choices=[('seed', 'Seed'), ('seed1', 'Seed1'), ('seed2', 'Seed2')], default='seed', max_length=255)),
                ('industry', models.CharField(choices=[('biotech', 'Biotech'), ('biotech1', 'Biotech1'), ('biotech2', 'Biotech2')], default='biotech', max_length=255)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('public1', 'Public1'), ('public2', 'Public2')], default='public', max_length=255)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('amd', 'AMD'), ('eur', 'EUR'), ('rub', 'RUB')], default='usd', max_length=255)),
                ('horizon', models.CharField(choices=[('3year', '<3year')], default='public', max_length=255)),
                ('capital_raised', models.IntegerField()),
                ('min_commitment', models.IntegerField()),
                ('leadership_commitment', models.IntegerField()),
                ('personal_note', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Syndicate',
            },
        ),
        migrations.CreateModel(
            name='SyndicateMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syndicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Syndicate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Syndicate Member',
            },
        ),
        migrations.AddField(
            model_name='invitedtosyndicate',
            name='syndicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Syndicate'),
        ),
    ]
